# Generated by Django 4.2.1 on 2023-05-30 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotel", "0002_hotel_activo_hotel_id_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Canales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Conexion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_canal", models.TextField()),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
                (
                    "id_canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.canales"
                    ),
                ),
                (
                    "id_hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habitaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "id_canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.canales"
                    ),
                ),
                (
                    "id_conexion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.conexion"
                    ),
                ),
            ],
        ),
    ]
