# Generated by Django 4.2.1 on 2023-06-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_canales_conexion_habitaciones"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlMonitoreos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_ejecucion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Monitoreos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_chkin", models.DateField()),
                ("canal", models.CharField(max_length=30)),
                ("habitacion", models.TextField()),
                ("precio", models.TextField()),
                (
                    "id_monitoreo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.controlmonitoreos",
                    ),
                ),
            ],
        ),
    ]
