# Generated by Django 4.2.1 on 2023-07-10 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_controlmonitoreos_monitoreos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monitoreos",
            old_name="id_monitoreo",
            new_name="id_monitoreo_p",
        ),
        migrations.RemoveField(
            model_name="monitoreos",
            name="precio",
        ),
        migrations.AddField(
            model_name="controlmonitoreos",
            name="fecha_monitoreo",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="controlmonitoreos",
            name="hora_monitoreo",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="controlmonitoreos",
            name="id_hotel",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoreos",
            name="moneda",
            field=models.CharField(default="MXN", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoreos",
            name="rango",
            field=models.CharField(default="0", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoreos",
            name="tarifa",
            field=models.FloatField(default="0"),
            preserve_default=False,
        ),
    ]
