# Generated by Django 4.2.1 on 2023-07-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0005_rename_id_monitoreo_monitoreos_id_monitoreo_p_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoreos",
            name="rango",
            field=models.CharField(max_length=30),
        ),
    ]
