# Generated by Django 4.2.1 on 2023-08-15 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0006_alter_monitoreos_rango"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDeCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora_t_cambio", models.DateTimeField()),
                ("tipo_cambio", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="conexion",
            name="id_canal",
        ),
        migrations.CreateModel(
            name="Incidencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incidencia", models.BooleanField()),
                (
                    "id_monitoreo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.monitoreos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HabitacionesHijas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                (
                    "id_canal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.canales"
                    ),
                ),
                (
                    "id_conexion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.conexion"
                    ),
                ),
                (
                    "id_habitacion_p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.habitaciones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AjustePreciosCanales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ajuste_exp", models.FloatField()),
                ("ajuste_bbk", models.FloatField()),
                (
                    "id_conexion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.conexion"
                    ),
                ),
            ],
        ),
    ]
