# Generated by Django 4.2.1 on 2023-08-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0007_tipodecambio_remove_conexion_id_canal_incidencias_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conexion",
            name="url_canal_bbk",
            field=models.TextField(blank=True, default="NA"),
        ),
        migrations.AddField(
            model_name="conexion",
            name="url_canal_exp",
            field=models.TextField(blank=True, default="NA"),
        ),
    ]
