# Generated by Django 4.2.1 on 2023-08-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0008_conexion_url_canal_bbk_conexion_url_canal_exp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestInsert_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=30)),
            ],
        ),
    ]
