# Generated by Django 4.2.1 on 2023-08-16 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0009_testinsert_1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testinsert_1",
            old_name="nombre_usuario",
            new_name="categoria_test",
        ),
        migrations.AddField(
            model_name="testinsert_1",
            name="edad_test",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testinsert_1",
            name="nombre_usuario_test",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
