# Generated by Django 4.2.1 on 2023-08-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0010_rename_nombre_usuario_testinsert_1_categoria_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="url_canal",
            field=models.TextField(default="NA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hotel",
            name="url_canal_bbk",
            field=models.TextField(blank=True, default="NA"),
        ),
        migrations.AddField(
            model_name="hotel",
            name="url_canal_exp",
            field=models.TextField(blank=True, default="NA"),
        ),
    ]
