# Generated by Django 4.2.1 on 2023-08-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0011_hotel_url_canal_hotel_url_canal_bbk_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="id_usuario",
        ),
    ]
