# Generated by Django 4.2.1 on 2023-08-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0012_remove_hotel_id_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habitacioneshijas",
            old_name="id_conexion",
            new_name="id_hotel",
        ),
        migrations.RemoveField(
            model_name="habitaciones",
            name="id_conexion",
        ),
        migrations.AddField(
            model_name="habitaciones",
            name="id_hotel",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
            ),
            preserve_default=False,
        ),
    ]
